// Copies the pdf.js runtime out of node_modules into src/renderer/vendor so the
// renderer can load it with a plain relative <script>/import, in dev and after packaging.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const dest = path.join(root, 'src', 'renderer', 'vendor');

function resolveDist() {
  const candidates = [
    path.join(root, 'node_modules', 'pdfjs-dist'),
    path.join(root, '..', 'node_modules', 'pdfjs-dist'),
  ];
  return candidates.find((p) => fs.existsSync(p));
}

const dist = resolveDist();
if (!dist) {
  console.warn('[vendor] pdfjs-dist not installed yet; skipping.');
  process.exit(0);
}

const wanted = [
  ['build/pdf.mjs', 'pdf.mjs'],
  ['build/pdf.worker.mjs', 'pdf.worker.mjs'],
];

fs.mkdirSync(dest, { recursive: true });

let copied = 0;
for (const [from, to] of wanted) {
  const src = path.join(dist, from);
  if (!fs.existsSync(src)) {
    console.error(`[vendor] missing ${from} in pdfjs-dist — check the installed version.`);
    process.exitCode = 1;
    continue;
  }
  fs.copyFileSync(src, path.join(dest, to));
  copied++;
}

// Standard fonts, needed to render PDFs that rely on the base-14 fonts.
const fontsSrc = path.join(dist, 'standard_fonts');
if (fs.existsSync(fontsSrc)) {
  fs.cpSync(fontsSrc, path.join(dest, 'standard_fonts'), { recursive: true });
}

// cmaps, needed for CJK text.
const cmapsSrc = path.join(dist, 'cmaps');
if (fs.existsSync(cmapsSrc)) {
  fs.cpSync(cmapsSrc, path.join(dest, 'cmaps'), { recursive: true });
}

console.log(`[vendor] copied ${copied} pdf.js file(s) to src/renderer/vendor`);

// pdf-lib does the actual merging, in the renderer, so vendor it the same way.
const pdfLib = path.join(root, 'node_modules', 'pdf-lib', 'dist', 'pdf-lib.esm.min.js');
if (fs.existsSync(pdfLib)) {
  fs.copyFileSync(pdfLib, path.join(dest, 'pdf-lib.esm.min.js'));
  console.log('[vendor] copied pdf-lib.esm.min.js');
} else {
  console.error('[vendor] missing pdf-lib dist build.');
  process.exitCode = 1;
}

// --- Inter -----------------------------------------------------------------
// The brand guide loads Inter from Google Fonts. A desktop app must render the
// same on a plane, so the identical face is bundled instead of fetched, which
// also keeps the renderer's CSP free of a font/style host.
const interSrc = path.join(
  root, 'node_modules', '@fontsource-variable', 'inter', 'files', 'inter-latin-wght-normal.woff2',
);
if (fs.existsSync(interSrc)) {
  fs.copyFileSync(interSrc, path.join(dest, 'inter-latin-wght-normal.woff2'));
  console.log('[vendor] copied Inter (latin, variable weight)');
} else {
  console.error('[vendor] missing @fontsource-variable/inter.');
  process.exitCode = 1;
}

// --- Lucide ----------------------------------------------------------------
// The brand guide specifies Lucide at stroke-width 2 in a 24 box. Rather than
// transcribing path data by hand, the exact icons used are extracted from
// lucide-static into one small module the renderer imports.
const LUCIDE_ICONS = [
  'file-plus-2', 'download', 'rotate-ccw', 'rotate-cw', 'trash-2', 'undo-2',
  'arrow-up-down', 'eraser', 'chevron-left', 'chevron-right', 'sun', 'moon', 'x', 'ellipsis',
];

const lucideDir = path.join(root, 'node_modules', 'lucide-static', 'icons');
if (fs.existsSync(lucideDir)) {
  const entries = [];
  for (const name of LUCIDE_ICONS) {
    const file = path.join(lucideDir, `${name}.svg`);
    if (!fs.existsSync(file)) {
      console.error(`[vendor] lucide icon not found: ${name}`);
      process.exitCode = 1;
      continue;
    }
    const svg = fs.readFileSync(file, 'utf8');
    const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
    entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(inner.replace(/\s+/g, ' '))},`);
  }
  fs.writeFileSync(
    path.join(dest, 'icons.js'),
    '// Generated by scripts/vendor.js from lucide-static (ISC). Do not edit.\n'
      + 'export const ICONS = {\n' + entries.join('\n') + '\n};\n',
  );
  console.log(`[vendor] wrote icons.js with ${entries.length} Lucide icons`);
} else {
  console.error('[vendor] missing lucide-static.');
  process.exitCode = 1;
}
